name: Continuous Integration
on:
  push:
    paths-ignore:
      - 'README.md'
      - 'architecture/**'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'architecture/**'

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: docker build --target test --tag todo-app:test .
    - run: docker run todo-app:test
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    if: |
      github.ref == 'refs/heads/exercise-9' ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker build --target production --platform linux/amd64 --tag ${{ secrets.DOCKER_USERNAME }}/todo-app:prod .
      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/todo-app:prod
      - name: Trigger Azure Deployment
        run: |
          curl -X POST ${{ secrets.AZURE_WEBHOOK_URL }}
        env:
          AZURE_WEBHOOK_URL: ${{ secrets.AZURE_WEBHOOK_URL }}
