name: Continuous Integration
on:
  push:
    paths-ignore:
      - 'README.md'
      - 'architecture/**'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'architecture/**'

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: docker build --target test --tag todo-app:test .
    - run: docker run todo-app:test
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - run: echo Publishing!
